export const ROLES = {
  COMPANY_OWNER: "COMPANY_OWNER",
  RECRUITER: "RECRUITER",
  CANDIDATE: "CANDIDATE",
};

export const APPLICATION_STATUS = {
  APPLIED: "APPLIED",
  SCREENING: "SCREENING",
  INTERVIEW: "INTERVIEW",
  OFFER: "OFFER",
  HIRED: "HIRED",
  REJECTED: "REJECTED",
};

export const JOB_STATUS = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
};

export const EMPLOYMENT_TYPE = {
  FULL_TIME: "FULL_TIME",
  PART_TIME: "PART_TIME",
  CONTRACT: "CONTRACT",
  INTERNSHIP: "INTERNSHIP",
};

export const WORKPLACE_TYPE = {
  ONSITE: "ONSITE",
  REMOTE: "REMOTE",
  HYBRID: "HYBRID",
};

export const EXPERIENCE_LEVEL = {
  ENTRY: "ENTRY",
  MID: "MID",
  SENIOR: "SENIOR",
  LEAD: "LEAD",
};
