const requiredEnvVars = [
  "PORT",
  "MONGO_URI",
  "ACCESS_TOKEN_SECRET",
  "ACCESS_TOKEN_EXPIRY",
  "REFRESH_TOKEN_SECRET",
  "REFRESH_TOKEN_EXPIRY",
  "API_BASE_URL",
  "CLIENT_URL",
  "GOOGLE_CLIENT_ID",
  "BREVO_API_KEY",
  "EMAIL_FROM_NAME",
  "EMAIL_FROM_ADDRESS",
  "EMAIL_BRAND_LOGO_URL",
  "PASSWORD_RESET_TOKEN_EXPIRY_MINUTES",
  "EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
  "GLOBAL_RATE_LIMIT_WINDOW_MINUTES",
  "GLOBAL_RATE_LIMIT_MAX_REQUESTS",
  "AUTH_RATE_LIMIT_WINDOW_MINUTES",
  "AUTH_RATE_LIMIT_MAX_REQUESTS",
  "AI_ENABLED",
  "AI_PROVIDER",
  "GEMINI_API_BASE_URL",
  "AI_REQUEST_TIMEOUT_MS",
  "AI_RESUME_ANALYSIS_DAILY_LIMIT",
  "AI_JOB_RESUME_FIT_DAILY_LIMIT",
  "AI_COMPANY_RESUME_REVIEW_DAILY_LIMIT",
  "AI_JOB_POST_SUGGESTION_DAILY_LIMIT",
  "AI_INTERVIEW_KIT_DAILY_LIMIT",
  "AI_SHORTLIST_DAILY_LIMIT",
  "AI_CANDIDATE_COMPARISON_DAILY_LIMIT",
  "AI_MAX_SHORTLIST_CANDIDATES",
  "AI_MAX_COMPARISON_CANDIDATES",
  "NODE_ENV",
];

const validateEnv = () => {
  const missing = requiredEnvVars.filter((key) => !process.env[key]);

  if (missing.length > 0) {
    console.error(
      `Missing required environment variables: ${missing.join(", ")}`,
    );
    process.exit(1);
  }
};

export default validateEnv;
